name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ !contains( join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run eslint
      - run: npm run test
      - run: npm run build

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment
        if: ${{ env.CONDITION == 'true' && github.event_name == 'push' }}
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true

  tag_release:
    if: ${{ github.env.CONDITION == 'true' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.71.0
      if: ${{ github.event_name == 'push' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch


#env:
#  CONDITION: ${{ !contains( join(github.event.commits.*.message), '#skip') }}
#
#jobs:
#  a_test_job:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v4
#      - name: github context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: commits
#        env:
#          COMMITS: ${{ toJson(github.event.commits) }}
#        run: echo "$COMMITS"
#      - name: commit messages
#        env:
#          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
#        run: echo "$COMMIT_MESSAGES"
#      - name: test skip
#        if: ${{ !contains( join(github.event.commits.*.message), '#skip') }}
#        run: echo "skip not found"
#      - name: test skip condition
#        if: ${{ env.CONDITION == 'true' }}
#        run: echo "skip not found condition"